baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"


[params]
title = "I'm AppLeeee"
profilePicture = "images/profile.jpg"

displayMode = "dark"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
